M48
; DRILL file {KiCad 9.0.3} date 2025-08-01T20:52:17+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-01T20:52:17+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X126.7Y-82.55
X126.7Y-109.55
X154.2Y-82.95
X154.2Y-109.55
M30
